InventorySystem/Areas/Admin/Controllers/BrandController.cs
using InventarySystem.DataAccess.Repository.IRepository;
using InventarySystem.Models;
using InventarySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventorySystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]
    public class BrandController : Controller
    {
        private readonly IWorkUnit _unitOfWork;

        public BrandController(IWorkUnit unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Brand brand = new Brand();

            if(id == null)
            {
                brand.State = true;
                return View(brand);
            }
            brand = await _unitOfWork.Brand.Retrieve(id.GetValueOrDefault());
            if(brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Brand brand)
        {
          if(ModelState.IsValid)
            {
                if(brand.Id == 0)
                {
                    await _unitOfWork.Brand.Add(brand);
                    TempData[DS.Success] = "Brand was created successfully";
                }
                else
                {
                    _unitOfWork.Brand.Update(brand);
                    TempData[DS.Success] = "Brand was updated successfully";
                }
                await _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Something went wrong with save";
            return View(brand);
        }

        #region API

        [HttpGet]
        public async Task<IActionResult> RetrieveAll()
        {
            var all = await _unitOfWork.Brand.RetrieveAll();
            return Json(new { data = all });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var brandDB = await _unitOfWork.Brand.Retrieve(id);
            if(brandDB == null)
            {
                return Json(new { success = false, message = "Error when deleting" });
            }
            _unitOfWork.Brand.Remove(brandDB);
            await _unitOfWork.Save();
            return Json(new { success = true, message = "Deleting was succesfully" });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
        {
            bool value = false;
            var list = await _unitOfWork.Brand.RetrieveAll();
            if(id == 0)
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                value = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim() && b.Id != id);
            }
            if(value)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }

        #endregion
    }
}

InventorySystem/Areas/Admin/Controllers/OrderController.cs
using InventarySystem.DataAccess.Repository.IRepository;
using InventarySystem.Models;
using InventarySystem.Models.ViewModels;
using InventarySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace InventorySystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IWorkUnit _workUnit;

        [BindProperty]
        private OrderDetailVM orderDetailVM { get; set; }

        public OrderController(IWorkUnit workUnit)
        {
            _workUnit = workUnit;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Detail(int id)
        {
            orderDetailVM = new OrderDetailVM()
            {
                Order = await _workUnit.Order.RetrieveFirst(o => o.Id == id, includeProperties: "UserApplication"),
                OrderDetailList = await _workUnit.OrderDetail.RetrieveAll(d => d.OrderId == id,
                                                                           includeProperties:"Product"),
            };
            return View(orderDetailVM);
        }

        [Authorize(Roles = DS.Role_Admin)]
        public async Task<IActionResult> Process(int id)
        {
            var order = await _workUnit.Order.RetrieveFirst(o => o.Id == id);
            order.OrderStatus = DS.InProcessStatus;
            await _workUnit.Save();
            TempData[DS.Success] = "Order was changed to in Process status";
            return RedirectToAction("Detail", new { id = id });
        }

        [Authorize(Roles = DS.Role_Admin)]
        public async Task<IActionResult> SubmitOrder(OrderDetailVM orderDetailVM)
        {
            var order = await _workUnit.Order.RetrieveFirst(o => o.Id == orderDetailVM.Order.Id);
            order.OrderStatus = DS.SentStatus;
            order.Carrier = orderDetailVM.Order.Carrier;
            order.ShippingNumber = orderDetailVM.Order.ShippingNumber;
            order.SendDate = DateTime.Now;
            await _workUnit.Save();
            TempData[DS.Success] = "Order was changed to sent status";
            return RedirectToAction("Detail", new { id = orderDetailVM.Order.Id });
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> RetrieveOrderList(string status)
        {
            //var all = await _workUnit.Order.RetrieveAll(includeProperties: "UserApplication");
            //return Json(new { data = all });
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            IEnumerable<Order> all;
            if (User.IsInRole(DS.Role_Admin)) // Validate the user role
            {
                all = await _workUnit.Order.RetrieveAll(includeProperties: "UserApplication");
            }
            else
            {
                all = await _workUnit.Order.RetrieveAll(o => o.UserApplicationId == claim.Value,includeProperties: "UserApplication");
            }
            // Validate the status
            switch (status)
            {
                case "approved":
                    all = all.Where(o => o.OrderStatus == DS.ApprovedStatus);
                    break;
                case "completed":
                    all = all.Where(o => o.OrderStatus == DS.SentStatus);
                    break;
                default:
                    break;
            }

            return Json(new { data = all });
        }
        #endregion
    }
}

InventorySystem/Areas/Admin/Controllers/StoreController.cs
using InventarySystem.DataAccess.Repository.IRepository;
using InventarySystem.Models;
using InventarySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InventorySystem.Areas.Admin.Controllers
{
    [Area("Admin")] // Always indicate the Area that belongs
    [Authorize(Roles = DS.Role_Admin)] 
    public class StoreController : Controller
    {
        private readonly IWorkUnit _unitedOfWork;

        public StoreController(IWorkUnit unitOfWork)
        {
            _unitedOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Store store = new Store();

            if(id==null)
            {
                //Create a new Store
                store.State = true;
                return View(store);
            }
            // Update Store
            store = await _unitedOfWork.Store.Retrieve(id.GetValueOrDefault());
            if(store == null)
            {
                return NotFound();
            }
            return View(store);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Avoid falsifyig requests to try load data 
        public async Task<IActionResult> Upsert(Store store)
        {
            if(ModelState.IsValid) // Validate that everything inside our Model comes right (props etc..)
            {
                if(store.Id == 0)
                {
                    await _unitedOfWork.Store.Add(store);
                    TempData[DS.Success] = "Store created successfully";
                }
                else
                {
                    _unitedOfWork.Store.Update(store);
                    TempData[DS.Success] = "Store updated successfully";
                }
                await _unitedOfWork.Save();
                return RedirectToAction(nameof(Index)); // In Write methods doesn't not return a View instead of we use redirect
            }
            TempData[DS.Error] = "Error saving";
            return View(store); // If doesn't apply changes redirect to the same views
        }


        #region API
        [HttpGet]
        public async Task<IActionResult> RetrieveAll()
        {
            var all = await _unitedOfWork.Store.RetrieveAll();
            return Json(new { data = all });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var storeDb = await _unitedOfWork.Store.Retrieve(id);
            if (storeDb == null)
            {
                return Json(new { success = false, message = "Something went wrong deleting" });
            }
            _unitedOfWork.Store.Remove(storeDb);
            await _unitedOfWork.Save();
            return Json(new { success = true, message = "Store deleted succesfully" });
        }

        [ActionName("ValidateName")]
        public async Task<IActionResult> ValidateName(string name, int id = 0)
        {
            bool val = false;
            var list = await _unitedOfWork.Store.RetrieveAll();
            if(id==0)
            {
                val = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim());
            }
            else
            {
                val = list.Any(b => b.Name.ToLower().Trim() == name.ToLower().Trim() && b.Id != id);
            }
            if(val)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }

        #endregion
    }
}

InventorySystem/Areas/Admin/Controllers/UserController.cs
using InventarySystem.DataAccess.Data;
using InventarySystem.DataAccess.Repository.IRepository;
using InventarySystem.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventorySystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = DS.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IWorkUnit _workOfUnit;
        private readonly ApplicationDbContext _db;

        public UserController(IWorkUnit workOfUnit, ApplicationDbContext db)
        {
            _workOfUnit = workOfUnit;
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region API

        [HttpGet]
        public async Task<IActionResult> RetrieveAll()
        {
            var userList = await _workOfUnit.UserApplication.RetrieveAll();
            var userRole = await _db.UserRoles.ToListAsync();
            var roles = await _db.Roles.ToListAsync();

            foreach (var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
            }

            return Json(new { data = userList });
        }

        [HttpPost]
        public async Task<IActionResult> LockAndUnlock([FromBody] string id)
        {
            var user = await _workOfUnit.UserApplication.RetrieveFirst(u => u.Id == id);
            if(user==null)
            {
                return Json(new { success = false, message = "User error" });
            }
            if(user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                // User Locked
                user.LockoutEnd = DateTime.Now;
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            await _workOfUnit.Save();
            return Json(new { success = true, message = "Operation was successfully" });
        }

        #endregion
    }
}

InventorySystem/Views/Shared/_ButtonsCreateAndBack.cshtml
<div class="d-grid gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false"><i class="bi bi-plus-square-fill"></i> Create</button>
    <a asp-action="Index" class="btn btn-success" > <i class="bi bi-arrow-return-left"></i> Back</a>
</div>

InventorySystem/Views/Shared/_Layout.cshtml
@using InventarySystem.Utilities
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventorySystem</title>
    <link rel="shortcut icon" href="~/images/icono.ico" />
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventorySystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet" />
    @* <link href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.css" rel="stylesheet" />  *@
    @* <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet">  *@
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.1.1/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/icono.png" width="50px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if(User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventory))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content
                                </a>
                                <ul class="dropdown-menu">
                                    @if(User.IsInRole(DS.Role_Admin))
                                    { 
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Store" asp-action="Index">Stores</a></li>
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a></li>
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index"> Brand</a></li>
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Upsert"> Company</a></li>
                                    }
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a></li>
                                </ul>
                            </li>
                        }   

                        @if(User.IsInRole(DS.Role_Admin))
                        {    
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">
                                    User
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a></li>
                                </ul>
                            </li>
                        }
                        @if(User.IsInRole(DS.Role_Admin) || User.IsInRole(DS.Role_Inventory))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">
                                    Inventory
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="Inventory" asp-controller="Inventory" asp-action="Index">Stock Products</a></li>
                                </ul>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>

                        @if(httpContextAccessor.HttpContext.Session.GetInt32(DS.ssShoppingCart) != null)
                        {
                            <li>
                                <a asp-area="Inventory" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    @{
                                        var productsAmount = httpContextAccessor.HttpContext.Session.GetInt32(DS.ssShoppingCart);
                                    }
                                    <i class="bi bi-cart-fill text-primary">&nbsp; (@productsAmount)</i>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a href="#" class="nav-link">
                                    <i class="bi bi-cart-fill text-primary">&nbsp; (0)</i>
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div >
        <main role="main" class="pb-2">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>
    <footer class="border-top text-muted">
        <div class="px-5">
            &copy; 2025 - InventorySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script> 
    @* <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script> *@

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InventorySystem/Views/Shared/_Notifications.cshtml
@using InventarySystem.Utilities

@if(TempData[DS.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Success]');
    </script>
}

@if(TempData[DS.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[DS.Error]');
    </script>
}

InventorySystem/Views/Shared/_buttonsUpdateAndBack.cshtml
@model int

<div class="d-grid gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false" asp-route-id="@Model"><i class="bi bi-pencil-square"></i> Update</button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left"></i> Back</a>
</div>